kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc-2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv-2
  labels:
    app: mongo 
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc-2
  awsElasticBlockStore:
    volumeID: vol-0072fdbd763db9571
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ebs-sc-2
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: mongo      
