apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-pod
  serviceName: "mongo"
  template:
    metadata:
      labels:
        app: mongo-pod
    spec:
      volumes:
      - name: mongopv1
        persistentVolumeClaim:
          claimName: mongo-vol-pvc1
      - name: mongopv2
        persistentVolumeClaim:
          claimName: mongo-vol-pvc2  
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongopv1
          mountPath: "/mnt/data1/"
        - name: mongopv2
          mountPath: "/mnt/data2/"  
--- 
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30313
  type: NodePort
  selector:
    app: mongo-pod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-vol-pvc1
spec:
  storageClassName: gp3
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-vol-pvc2
spec:
  storageClassName: gp3
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
