apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-2
  labels:
    app: wordpress-2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0db83c06a8e01ce77
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: wordpress-2